### PR TITLE
Let's do this lmao

### PR DESCRIPTION
**Pull request by IgorAlexey**
Probably useless boilerplate, but can get us somewhere, no?

I have little python knowledge

### CODE REVIEW

**Comment by matveitolochko** [comment]
@Sororfortuna could you help me in [my fork](https://github.com/AtomicGamer9523/rektor-db), basically redo [chroma](https://github.com/chroma-core/chroma) in rust ;)

**Comment by conaticus** [comment]
-1 for not using rust

**Comment by IgorAlexey** [comment]
> @Sororfortuna could you help me in [my fork](https://github.com/AtomicGamer9523/rektor-db), basically redo [chroma](https://github.com/chroma-core/chroma) in rust ;)

Alright I actually like, I may contribute some in a while, I like the idea of Rust better than Python, as I can work on some interoperability with my existing C++ codebase

**Comment by matveitolochko** [comment]
sounds good

**Review by TheLime1 — APPROVED** [review]
who am i but i approve

**Pull request closed without merging**
