### PR TITLE
major improvement: added rust

### PR DESCRIPTION
**Pull request by ghost**
100x improvement

### CODE REVIEW

**Review by Swissforce — APPROVED** [review]
closes #11

**Comment by matveitolochko** [comment]
hey @MrPiggyPegasus could you please help me out in [my fork](https://github.com/AtomicGamer9523/rektor-db), it will be in rust ;)

**Comment by sarc143** [comment]
Suggestion: Translate to asseembly. Machine code. mmmgphhh.....

Suggestoin 2: Code in COBOL. Classic Language. Proven.

**Review by ricardo-rp — APPROVED** [review]
LGBT

**Comment by sarc143** [comment]
I agree Ricardo. Lets Get Back TO IT!!! I want all these databases translated to assembly, no, binary. PRONTO. FIGURE IT OUT.

**Comment by ricardo-rp** [comment]
> I agree Ricardo. Lets Get Back TO IT!!! I want all these databases translated to assembly, no, binary. PRONTO. FIGURE IT OUT.

No, I meant looks good to me

**Comment by Vtchoo** [comment]
ran it on my machine and it's blazingly fast LGTM 👍

**Pull request closed without merging**
