### PR TITLE
Creating package.json and wrote my self as contributor (money will be distributed between author and contributors)

### PR DESCRIPTION
**Pull request by urosjarc**
I invest in to the code... And since package.json is more important than README.md file I will become 75% shareholder of this project.

1_4bw__q_YPonUBVfnEymj8A

### CODE REVIEW

**Comment by lesleyxyz** [comment]
Hi, before I approve this PR, could you add me as contributor? I have future plans to be a big contributor

**Review by lesleyxyz — CHANGES_REQUESTED** [review]
Hi, before I approve this PR, could you add me as contributor? I have future plans to be a big contributor

**Comment by urosjarc** [comment]
@lesleyxyz 
CreamyLegalBordercollie-max-1mb

**Comment by matveitolochko** [comment]
This is great ;)

**Pull request closed without merging**
